### ISSUE TITLE
CanadaRP

### ISSUE THREAD

**Issue by irefl** [BillardDRP/nathaniel-rp-website#1]
rip darkRP garry newman just died of shame

**Comment by SirFrancisBillard** [comment]
garry newman AND fpjte

**Comment by irefl** [comment]
also you may want to change the repo name to what what you want it to be or else the url will be like BillardDRP.github.io/nathaniel-rp and cname files are fucked for me

**Comment by SirFrancisBillard** [comment]
It won't really matter, the only time the site shows up is in the loading screen and when you type !website

**Comment by irefl** [comment]
ik but ocd

**Comment by SirFrancisBillard** [comment]
This is gmod m8, an utter clusterfuck of lua. No time for that to waste on fixing a website when there are literally thousands of shits in the lua.

**Comment by irefl** [comment]
prbly why I cut myself when i try to write it

**Comment by irefl** [comment]
toot
